---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "ack-sagemaker-controller.app.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-sagemaker-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-sagemaker-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-sagemaker-controller.chart.name-version" . }}
rules:
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - apps
  - dataqualityjobdefinitions
  - domains
  - endpoints
  - endpointconfigs
  - featuregroups
  - hyperparametertuningjobs
  - inferencecomponents
  - labelingjobs
  - models
  - modelbiasjobdefinitions
  - modelexplainabilityjobdefinitions
  - modelpackages
  - modelpackagegroups
  - modelqualityjobdefinitions
  - monitoringschedules
  - notebookinstances
  - notebookinstancelifecycleconfigs
  - pipelines
  - pipelineexecutions
  - processingjobs
  - projects
  - spaces
  - trainingjobs
  - transformjobs
  - userprofiles
  verbs:
  - get
  - list
  - watch
