---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ack-sagemaker-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - apps
  - dataqualityjobdefinitions
  - domains
  - endpointconfigs
  - endpoints
  - featuregroups
  - hyperparametertuningjobs
  - inferencecomponents
  - modelbiasjobdefinitions
  - modelexplainabilityjobdefinitions
  - modelpackagegroups
  - modelpackages
  - modelqualityjobdefinitions
  - models
  - monitoringschedules
  - notebookinstancelifecycleconfigs
  - notebookinstances
  - pipelineexecutions
  - pipelines
  - processingjobs
  - trainingjobs
  - transformjobs
  - userprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - apps/status
  - dataqualityjobdefinitions/status
  - domains/status
  - endpointconfigs/status
  - endpoints/status
  - featuregroups/status
  - hyperparametertuningjobs/status
  - inferencecomponents/status
  - modelbiasjobdefinitions/status
  - modelexplainabilityjobdefinitions/status
  - modelpackagegroups/status
  - modelpackages/status
  - modelqualityjobdefinitions/status
  - models/status
  - monitoringschedules/status
  - notebookinstancelifecycleconfigs/status
  - notebookinstances/status
  - pipelineexecutions/status
  - pipelines/status
  - processingjobs/status
  - trainingjobs/status
  - transformjobs/status
  - userprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
