
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-sagemaker-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - dataqualityjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - dataqualityjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpointconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpointconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - hyperparametertuningjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - hyperparametertuningjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelbiasjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelbiasjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelexplainabilityjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelexplainabilityjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelqualityjobdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - modelqualityjobdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - monitoringschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - monitoringschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - processingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - processingjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - trainingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - trainingjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - transformjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - transformjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
