---
annotations:
  capabilityLevel: Basic Install
  shortDescription: ACK service controller for Amazon SageMaker manages
    SageMaker resources in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon SageMaker
description: |-
  Manage Amazon SageMaker resources in AWS from within your Kubernetes cluster.


  **About Amazon SageMaker**


  Amazon SageMaker helps data scientists and developers to prepare, build,
  train, and deploy high-quality machine learning (ML) models quickly by
  bringing together a broad set of capabilities purpose-built for ML.

  
  For more information on Amazon SageMaker, visit the [product
  page](https://aws.amazon.com/sagemaker/).


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for
  Kubernetes](https://github.com/aws/aws-controllers-k8s)project. This project
  is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: DataQualityJobDefinition
  spec: '{}'
- kind: EndpointConfig
  spec: '{}'
- kind: Endpoint
  spec: '{}'
- kind: HyperParameterTuningJob
  spec: '{}'
- kind: ModelBiasJobDefinition
  spec: '{}'
- kind: ModelExplainabilityJobDefinition
  spec: '{}'
- kind: ModelQualityJobDefinition
  spec: '{}'
- kind: Model
  spec: '{}'
- kind: MonitoringSchedule
  spec: '{}'
- kind: ProcessingJob
  spec: '{}'
- kind: TrainingJob
  spec: '{}'
- kind: TransformJob
  spec: '{}'
maintainers:
- name: "sagemaker maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon SageMaker Developer Resources
  url: https://aws.amazon.com/sagemaker/developer-resources/
