apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/sagemaker.services.k8s.aws_endpoints.yaml
  - bases/sagemaker.services.k8s.aws_endpointconfigs.yaml
  - bases/sagemaker.services.k8s.aws_models.yaml
  - bases/sagemaker.services.k8s.aws_processingjobs.yaml
  - bases/sagemaker.services.k8s.aws_trainingjobs.yaml
  - bases/sagemaker.services.k8s.aws_transformjobs.yaml
