apiVersion: v1
name: sagemaker-chart
description: A Helm chart for the ACK service controller for Amazon SageMaker (SageMaker)
version: 1.2.4
appVersion: 1.2.4
home: https://github.com/aws-controllers-k8s/sagemaker-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/sagemaker-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: SageMaker Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/sagemaker-maintainer
keywords:
  - aws
  - kubernetes
  - sagemaker
