apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: Project
metadata:
  name: sbuasai-ack-project
spec:
  projectName: sbuasai-ack-project
  serviceCatalogProvisioningDetails:
    productID: prod-6sx3gpcyxek2y
    provisioningArtifactID: pa-4pkofsezeia22
    provisioningParameters:
      - key: ModelBuildCodeRepositoryBranch
        value: main
      - key: ModelBuildCodeRepositoryFullname
        value: sirutBuasai/tmp-test
      - key: CodeConnectionArn
        value: arn:aws:codeconnections:us-west-2:897880167187:connection/a63dd9d5-8cc0-4df9-8851-8ff6ab190d1e
